# Generated by Django 5.1.7 on 2026-09-15 07:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "deleted",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("reference_id", models.CharField(db_index=True, max_length=255)),
                ("rung", models.CharField(db_index=True, max_length=64)),
                ("dataset_version", models.CharField(db_index=True, max_length=64)),
                ("seed", models.IntegerField(default=1)),
                ("steps", models.IntegerField(blank=True, null=True)),
                ("environment", models.CharField(db_index=True, default="local", max_length=32)),
                ("stage", models.CharField(db_index=True, default="SCHEDULED", max_length=255)),
                ("status", models.CharField(db_index=True, default="SCHEDULED", max_length=128)),
                ("executor", models.CharField(default="ecs", max_length=32)),
                ("ecs_cluster", models.CharField(blank=True, default="", max_length=255)),
                (
                    "ecs_task_arn",
                    models.CharField(blank=True, db_index=True, default="", max_length=512),
                ),
                ("execution_started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("error_logs", models.JSONField(blank=True, default=dict)),
                ("time_logs", models.JSONField(blank=True, default=dict)),
                ("run_logs", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
