#!/usr/bin/env python3
"""Regenerate ``src/roto/data/elements.py`` from the layer->channel matcher.

The layer->matte-channel mapping is recovered knowledge, not archive data: it lived in a
Nuke script that was never delivered. So it belongs *checked in and reviewable*, not
re-derived on every run -- both because matching costs minutes and because a silently
changed mapping would silently change every downstream number.

Run this when the matcher changes, a shot is added, or a mapping is disputed:

    PYTHONPATH=src python scripts/discover_elements.py --scale 0.35 --stride 10

Then read the diff before committing it.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'src'))

from roto.data.shots import find_shots                                  # noqa: E402
from roto.eval.match import assign_channels, element_doc                # noqa: E402
from roto.eval.metrics import error_profile, iou, soft_iou              # noqa: E402
from roto.matte.exr import load_channels                                # noqa: E402
from roto.render.raster import RenderConfig, render_union               # noqa: E402
from roto.sfx.read import read_sfx                                      # noqa: E402

VERIFIED_IOU = 0.97
PROVISIONAL_IOU = 0.95

# Shots excluded on evidence rather than score. Keep the reason with the exclusion.
BLOCKED_SHOTS = {
    'TVC_SHOTS_sh0230_BG01_v003_roto_v02':
        'delivered matte was rendered from a different save than the archived project '
        '(hair animates ~20 frames past the last key); also 87% single-frame hair strokes',
}

HEADER = '''"""Recovered (layer union) -> (matte channel) mapping, with measured fidelity.

GENERATED by ``scripts/discover_elements.py`` -- do not hand-edit; regenerate and read the
diff. The mapping is not in the archive: the Silhouette layers were rendered per-layer and a
Nuke script packed them into R/G/B channels, and that script was not delivered. Everything
here was recovered by search and then scored against the delivered EXRs.

``tier`` is what Phase 0 selects on:

* ``verified``    -- mean IoU >= {v}, safe as a training target
* ``provisional`` -- mean IoU >= {p}, usable but worth a look first
* ``excluded``    -- below that, or blocked on evidence (see ``note``)

Layers matched at scale {scale}; fidelity scored at scale {score_scale} on every
{stride}th frame. The scoring scale matters: at scale 0.35 the same elements read up to
0.02 IoU lower, because comparing a downscaled render against a cv2-downscaled EXR carries
a half-pixel convention mismatch. Scoring below full resolution understates everything.

``uuids`` are the stable ids; ``labels`` are for humans and can collide.
"""
from __future__ import annotations

from dataclasses import dataclass

VERIFIED_IOU = {v}
PROVISIONAL_IOU = {p}


@dataclass(frozen=True, slots=True)
class Element:
    """One deliverable matte channel and the layer union that produces it."""
    element_id: str
    shot: str
    matte: str
    channel: str
    labels: tuple[str, ...]
    uuids: tuple[str, ...]
    tier: str
    mean_iou: float
    min_iou: float
    mean_soft_iou: float
    frames_tested: int
    worst_frame: int
    worst_edge_only: bool
    note: str = ''

    @property
    def is_target(self) -> bool:
        """Usable as a Phase 0 training target."""
        return self.tier in ('verified', 'provisional')


ELEMENTS: tuple[Element, ...] = (
'''


def element_id(shot: str, matte: str, channel: str) -> str:
    """Short, stable, filesystem-safe. Long vendor matte names collapse to their suffix."""
    short = matte
    for marker in ('_matte_', '_matte'):
        if marker in matte:
            short = 'matte' + matte.split(marker, 1)[1].split('_v')[0]
            break
    return f'{shot.split("_roto_v")[0][:34]}__{short}__{channel}'


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--data-root', default='data/extracted/test_data')
    ap.add_argument('--scale', type=float, default=0.35,
                    help='scale for the cheap layer->channel MATCHING pass')
    ap.add_argument('--score-scale', type=float, default=1.0,
                    help='scale for the SCORING pass. Keep at 1.0: comparing a downscaled '
                         'render against a cv2-downscaled EXR carries a half-pixel '
                         'convention mismatch worth up to ~0.02 IoU, all of it at the '
                         'boundary, which understates every score.')
    ap.add_argument('--stride', type=int, default=10)
    ap.add_argument('-o', '--output', default='src/roto/data/elements.py')
    args = ap.parse_args()

    cfg = RenderConfig()
    rows = []
    for shot in find_shots(args.data_root):
        doc = read_sfx(shot.sfx)
        blocked = BLOCKED_SHOTS.get(shot.name)
        print(f'\n=== {shot.name} ===', flush=True)
        for a in assign_channels(doc, shot.mattes, scale=args.scale,
                                 sample_frames=shot.sample_frames(3), cfg=cfg):
            sub = element_doc(doc, a.members)
            frames = sorted(shot.mattes[a.matte])[::args.stride]
            ious, softs, worst = [], [], (2.0, None)
            for f in frames:
                truth = load_channels(shot.mattes[a.matte][f],
                                      args.score_scale).get(a.channel)
                if truth is None:
                    continue
                pred = render_union(sub, f - doc.start_frame, cfg, args.score_scale)
                if pred.shape != truth.shape:
                    continue
                v = iou(pred, truth)
                ious.append(v)
                softs.append(soft_iou(pred, truth))
                if v < worst[0]:
                    worst = (v, (f, pred, truth))
            if not ious:
                continue
            mean = float(np.mean(ious))
            prof = error_profile(worst[1][1], worst[1][2])
            if blocked:
                tier, note = 'excluded', blocked
            elif mean >= VERIFIED_IOU:
                tier, note = 'verified', ''
            elif mean >= PROVISIONAL_IOU:
                tier, note = 'provisional', f'mean IoU {mean:.3f} below {VERIFIED_IOU}'
            else:
                tier, note = 'excluded', f'mean IoU {mean:.3f} below {PROVISIONAL_IOU}'
            rows.append(dict(
                element_id=element_id(shot.name, a.matte, a.channel), shot=shot.name,
                matte=a.matte, channel=a.channel,
                labels=tuple(c.label for c in a.members),
                uuids=tuple(c.layer.uuid or '' for c in a.members),
                tier=tier, mean_iou=mean, min_iou=float(np.min(ious)),
                mean_soft_iou=float(np.mean(softs)), frames_tested=len(ious),
                worst_frame=int(worst[1][0]), worst_edge_only=bool(prof.is_edge_only),
                note=note))
            print(f'  {a.matte} [{a.channel}] {tier:12} IoU {mean:.4f} '
                  f'min {np.min(ious):.3f} soft {np.mean(softs):.3f} <- {a.label}', flush=True)

    rows.sort(key=lambda r: (r['tier'] != 'verified', r['tier'] != 'provisional',
                             -r['mean_iou']))
    body = []
    for r in rows:
        body.append('    Element(\n' + ''.join(
            f'        {k}={v!r},\n' for k, v in r.items()) + '    ),\n')

    out = Path(args.output)
    out.write_text(
        HEADER.format(v=VERIFIED_IOU, p=PROVISIONAL_IOU, scale=args.scale,
                      score_scale=args.score_scale, stride=args.stride)
        + ''.join(body)
        + ')\n\nTARGETS: tuple[Element, ...] = tuple(e for e in ELEMENTS if e.is_target)\n'
          '\n\ndef by_id(element_id: str) -> Element:\n'
          '    for e in ELEMENTS:\n'
          '        if e.element_id == element_id:\n'
          '            return e\n'
          '    raise KeyError(f\'no element {element_id!r}; have '
          '{[e.element_id for e in ELEMENTS]}\')\n')
    counts = {t: sum(1 for r in rows if r['tier'] == t)
              for t in ('verified', 'provisional', 'excluded')}
    print(f'\nwrote {out}: {counts}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
