"""Recovered (layer union) -> (matte channel) mapping, with measured fidelity.

GENERATED by ``scripts/discover_elements.py`` -- do not hand-edit; regenerate and read the
diff. The mapping is not in the archive: the Silhouette layers were rendered per-layer and a
Nuke script packed them into R/G/B channels, and that script was not delivered. Everything
here was recovered by search and then scored against the delivered EXRs.

``tier`` is what Phase 0 selects on:

* ``verified``    -- mean IoU >= 0.97, safe as a training target
* ``provisional`` -- mean IoU >= 0.95, usable but worth a look first
* ``excluded``    -- below that, or blocked on evidence (see ``note``)

Layers matched at scale 0.35; fidelity scored at scale 1.0 on every
10th frame. The scoring scale matters: at scale 0.35 the same elements read up to
0.02 IoU lower, because comparing a downscaled render against a cv2-downscaled EXR carries
a half-pixel convention mismatch. Scoring below full resolution understates everything.

``uuids`` are the stable ids; ``labels`` are for humans and can collide.
"""
from __future__ import annotations

from dataclasses import dataclass

VERIFIED_IOU = 0.97
PROVISIONAL_IOU = 0.95


@dataclass(frozen=True, slots=True)
class Element:
    """One deliverable matte channel and the layer union that produces it."""
    element_id: str
    shot: str
    matte: str
    channel: str
    labels: tuple[str, ...]
    uuids: tuple[str, ...]
    tier: str
    mean_iou: float
    min_iou: float
    mean_soft_iou: float
    frames_tested: int
    worst_frame: int
    worst_edge_only: bool
    note: str = ''

    @property
    def is_target(self) -> bool:
        """Usable as a Phase 0 training target."""
        return self.tier in ('verified', 'provisional')


ELEMENTS: tuple[Element, ...] = (
    Element(
        element_id='MAT_0130_L1_C002_260809_v001__matte01__R',
        shot='MAT_0130_L1_C002_260809_v001',
        matte='matte01',
        channel='R',
        labels=('Red Matte/Layer',),
        uuids=('8126d5fa-8f2c-43f6-b430-d9f6fd17e8ee',),
        tier='verified',
        mean_iou=0.9979513109973649,
        min_iou=0.9976580293068626,
        mean_soft_iou=0.9975472120749221,
        frames_tested=6,
        worst_frame=1021,
        worst_edge_only=True,
        note='',
    ),
    Element(
        element_id='FAM_0060_L1_A0003C007_v001__matte02__B',
        shot='FAM_0060_L1_A0003C007_v001',
        matte='matte02',
        channel='B',
        labels=('blue',),
        uuids=('1a7a669c-8b5b-464a-954e-5ab4deccdcf5',),
        tier='verified',
        mean_iou=0.9973326860960097,
        min_iou=0.9944139329403392,
        mean_soft_iou=0.9961273377851753,
        frames_tested=14,
        worst_frame=1011,
        worst_edge_only=True,
        note='',
    ),
    Element(
        element_id='nfl_0200_bg01_v001_compplate__matte01__R',
        shot='nfl_0200_bg01_v001_compplate_roto_v001',
        matte='matte01',
        channel='R',
        labels=('blue',),
        uuids=('67d7ac13-9157-4644-b115-488d492921f8',),
        tier='verified',
        mean_iou=0.9943535000821354,
        min_iou=0.9917368372351254,
        mean_soft_iou=0.9929689470021945,
        frames_tested=20,
        worst_frame=1101,
        worst_edge_only=True,
        note='',
    ),
    Element(
        element_id='nfl_0080_bg02_v001_compplate__matte01__R',
        shot='nfl_0080_bg02_v001_compplate_roto_v001',
        matte='matte01',
        channel='R',
        labels=('mb 1/red',),
        uuids=('34e9ef0d-fac5-4c19-843f-3030b434f64e',),
        tier='verified',
        mean_iou=0.9929801601066356,
        min_iou=0.9922937812606918,
        mean_soft_iou=0.9922676503361264,
        frames_tested=16,
        worst_frame=1061,
        worst_edge_only=False,
        note='',
    ),
    Element(
        element_id='TVC_SHOTS_sh0260_BG01_v003__matteL110__R',
        shot='TVC_SHOTS_sh0260_BG01_v003_roto_v02',
        matte='TVC_SHOTS_sh0260_BG01_v003_matte_L110_v02',
        channel='R',
        labels=('Layer 52/body/Layer 1', 'Layer 52/body/RED'),
        uuids=('76af5297-5372-4a2c-bb3c-ce1b77f7d4f1', 'd6f658de-55f4-408d-8c21-6060aea001f3'),
        tier='verified',
        mean_iou=0.9897909176292455,
        min_iou=0.965646600106339,
        mean_soft_iou=0.9823247191463044,
        frames_tested=8,
        worst_frame=1041,
        worst_edge_only=False,
        note='',
    ),
    Element(
        element_id='FAM_0060_L1_A0003C007_v001__matte02__R',
        shot='FAM_0060_L1_A0003C007_v001',
        matte='matte02',
        channel='R',
        labels=('red/wall/Layer 3',),
        uuids=('0ee18e88-a94d-4aa2-869b-c2d597d37e40',),
        tier='verified',
        mean_iou=0.9861331810530587,
        min_iou=0.9740142677105605,
        mean_soft_iou=0.9861906511810409,
        frames_tested=14,
        worst_frame=1001,
        worst_edge_only=False,
        note='',
    ),
    Element(
        element_id='nfl_0200_bg01_v001_compplate__matte01__G',
        shot='nfl_0200_bg01_v001_compplate_roto_v001',
        matte='matte01',
        channel='G',
        labels=('green/hair/Layer',),
        uuids=('c7aee2d7-d6ef-4d54-b77e-dba81bb9895e',),
        tier='verified',
        mean_iou=0.9858493876688321,
        min_iou=0.9820419693301049,
        mean_soft_iou=0.9833601826160375,
        frames_tested=20,
        worst_frame=1181,
        worst_edge_only=True,
        note='',
    ),
    Element(
        element_id='FAM_0060_L1_A0003C007_v001__matte01__G',
        shot='FAM_0060_L1_A0003C007_v001',
        matte='matte01',
        channel='G',
        labels=('green',),
        uuids=('a87b1d07-6f99-413d-a636-2413c600ba30',),
        tier='verified',
        mean_iou=0.9857756394124572,
        min_iou=0.9112575763310282,
        mean_soft_iou=0.9843956092793716,
        frames_tested=14,
        worst_frame=1001,
        worst_edge_only=False,
        note='',
    ),
    Element(
        element_id='FAM_0060_L1_A0003C007_v001__matte01__B',
        shot='FAM_0060_L1_A0003C007_v001',
        matte='matte01',
        channel='B',
        labels=('blue 1',),
        uuids=('f6f25994-27e5-4232-b660-4cc6421ef0bf',),
        tier='verified',
        mean_iou=0.9842984999272086,
        min_iou=0.9772431774887949,
        mean_soft_iou=0.9814455874504194,
        frames_tested=14,
        worst_frame=1101,
        worst_edge_only=False,
        note='',
    ),
    Element(
        element_id='FAM_0060_L1_A0003C007_v001__matte02__G',
        shot='FAM_0060_L1_A0003C007_v001',
        matte='matte02',
        channel='G',
        labels=('green 2', 'r1_w_c', 'green 1', 'r1_t_c/CH4/Layer 72'),
        uuids=('55e88c09-5bfa-420c-b00e-7ea6233c4968', '93550b6e-be3d-4e64-80b4-64ac70b76f48', 'b6588a9b-6ddf-4c6f-b06a-dd28bea22a5b', '5d1e9431-d77e-47df-a840-75139ad80fbc'),
        tier='excluded',
        mean_iou=0.9369336063293597,
        min_iou=0.7263904606806701,
        mean_soft_iou=0.9363667163936868,
        frames_tested=14,
        worst_frame=1131,
        worst_edge_only=False,
        note='mean IoU 0.937 below 0.95',
    ),
    Element(
        element_id='FAM_0060_L1_A0003C007_v001__matte01__R',
        shot='FAM_0060_L1_A0003C007_v001',
        matte='matte01',
        channel='R',
        labels=('red 1',),
        uuids=('4099e2d4-56e9-4cd3-9cc0-22ecdbb8a99a',),
        tier='excluded',
        mean_iou=0.8852207345299393,
        min_iou=0.8740398277067563,
        mean_soft_iou=0.8874865900838252,
        frames_tested=14,
        worst_frame=1131,
        worst_edge_only=False,
        note='mean IoU 0.885 below 0.95',
    ),
    Element(
        element_id='nfl_0080_bg02_v001_compplate__matte01__G',
        shot='nfl_0080_bg02_v001_compplate_roto_v001',
        matte='matte01',
        channel='G',
        labels=('mb 1/green/core', 'mb 1/green/Core'),
        uuids=('b485f3fd-ffd0-40cc-9fbe-ba54b57816db', '10fb2c53-cb67-4b9f-b3c5-bd5d3a338800'),
        tier='excluded',
        mean_iou=0.8845249999698571,
        min_iou=0.18092802941037847,
        mean_soft_iou=0.8847484470264346,
        frames_tested=16,
        worst_frame=1001,
        worst_edge_only=False,
        note='mean IoU 0.885 below 0.95',
    ),
    Element(
        element_id='nfl_0080_bg02_v001_compplate__matte01__B',
        shot='nfl_0080_bg02_v001_compplate_roto_v001',
        matte='matte01',
        channel='B',
        labels=('mb 1/blue/sholder', 'mb 1/blue/Layer 3', 'mb 1/blue/Layer 36', 'mb 1/blue/CHAR ', 'mb 1/blue/hand'),
        uuids=('8ad6963c-3587-4e64-802a-fc5b487fd795', 'ef09f40a-90c2-4403-b925-fce4afbaaf56', '008820f4-333e-4bfd-bb23-577ec6a9f20a', 'b84a992f-d2c1-4869-88b0-ca20d85b2756', '65e52695-e7dc-4352-9702-e70917b944c0'),
        tier='excluded',
        mean_iou=0.8710166303757256,
        min_iou=0.6964711656237588,
        mean_soft_iou=0.8706997399423863,
        frames_tested=15,
        worst_frame=1021,
        worst_edge_only=False,
        note='mean IoU 0.871 below 0.95',
    ),
    Element(
        element_id='TVC_SHOTS_sh0260_BG01_v003__matteL120__R',
        shot='TVC_SHOTS_sh0260_BG01_v003_roto_v02',
        matte='TVC_SHOTS_sh0260_BG01_v003_matte_L120_v02',
        channel='R',
        labels=('Layer 52/shadow/Layer 29',),
        uuids=('0cadb31d-98d3-499a-9ad4-767e088cdb52',),
        tier='excluded',
        mean_iou=0.8360495379515778,
        min_iou=0.2515625,
        mean_soft_iou=0.8263817103228801,
        frames_tested=5,
        worst_frame=1041,
        worst_edge_only=False,
        note='mean IoU 0.836 below 0.95',
    ),
    Element(
        element_id='TVC_SHOTS_sh0260_BG01_v003__matteL110__B',
        shot='TVC_SHOTS_sh0260_BG01_v003_roto_v02',
        matte='TVC_SHOTS_sh0260_BG01_v003_matte_L110_v02',
        channel='B',
        labels=('Layer 52/details',),
        uuids=('88ea9ac6-6d78-4564-8b5a-fab56e86392c',),
        tier='excluded',
        mean_iou=0.8087751413956746,
        min_iou=0.7771558245083208,
        mean_soft_iou=0.7656275858320389,
        frames_tested=8,
        worst_frame=1071,
        worst_edge_only=False,
        note='mean IoU 0.809 below 0.95',
    ),
    Element(
        element_id='TVC_SHOTS_sh0260_BG01_v003__matteL100__G',
        shot='TVC_SHOTS_sh0260_BG01_v003_roto_v02',
        matte='TVC_SHOTS_sh0260_BG01_v003_matte_L100_v02',
        channel='G',
        labels=('Layer 52/body/Layer 21', 'Layer 52/body/Layer 33', 'Layer 52/body/Layer 31', 'Layer 52/body/Layer 32'),
        uuids=('236a4416-2b8a-4b7d-94f0-192b9273ffb3', '02335443-9f73-4d29-8831-018a3efe220f', '9c43f056-bcae-4648-901d-9fed0570dd8d', '4f1b60f7-b8bb-48ea-9081-e491dad5801e'),
        tier='excluded',
        mean_iou=0.7004273234351197,
        min_iou=0.28030237952065973,
        mean_soft_iou=0.6840449444273091,
        frames_tested=8,
        worst_frame=1021,
        worst_edge_only=False,
        note='mean IoU 0.700 below 0.95',
    ),
    Element(
        element_id='TVC_SHOTS_sh0260_BG01_v003__matteL100__R',
        shot='TVC_SHOTS_sh0260_BG01_v003_roto_v02',
        matte='TVC_SHOTS_sh0260_BG01_v003_matte_L100_v02',
        channel='R',
        labels=('Layer 52/body',),
        uuids=('70a18851-a0b4-48b9-8248-4819e75ac260',),
        tier='excluded',
        mean_iou=0.5130833214120198,
        min_iou=0.4074212374602988,
        mean_soft_iou=0.5105718150667109,
        frames_tested=8,
        worst_frame=1001,
        worst_edge_only=False,
        note='mean IoU 0.513 below 0.95',
    ),
    Element(
        element_id='TVC_SHOTS_sh0260_BG01_v003__matteL110__G',
        shot='TVC_SHOTS_sh0260_BG01_v003_roto_v02',
        matte='TVC_SHOTS_sh0260_BG01_v003_matte_L110_v02',
        channel='G',
        labels=('Layer 52/body/Layer 27', 'Layer 52/body/Layer 31'),
        uuids=('86ebd3ff-54f1-4b14-b317-2bac9f7e7c8d', '193a1247-da27-4645-972f-a6d763071c74'),
        tier='excluded',
        mean_iou=0.36912989456191214,
        min_iou=0.22121541787735655,
        mean_soft_iou=0.3675458225448322,
        frames_tested=8,
        worst_frame=1071,
        worst_edge_only=False,
        note='mean IoU 0.369 below 0.95',
    ),
    Element(
        element_id='TVC_SHOTS_sh0260_BG01_v003__matteL100__B',
        shot='TVC_SHOTS_sh0260_BG01_v003_roto_v02',
        matte='TVC_SHOTS_sh0260_BG01_v003_matte_L100_v02',
        channel='B',
        labels=('Layer 52/body/Char',),
        uuids=('22b62e6c-7bc2-4080-ac08-97a3d1c5ba12',),
        tier='excluded',
        mean_iou=0.2635930334758938,
        min_iou=0.18605669736222585,
        mean_soft_iou=0.26272758053905987,
        frames_tested=8,
        worst_frame=1061,
        worst_edge_only=False,
        note='mean IoU 0.264 below 0.95',
    ),
    Element(
        element_id='nfl_0080_bg02_v001_compplate__matte02__R',
        shot='nfl_0080_bg02_v001_compplate_roto_v001',
        matte='matte02',
        channel='R',
        labels=('MB 2/RED /Open',),
        uuids=('e30f346d-75ed-4be9-b5f7-26734853e7bc',),
        tier='excluded',
        mean_iou=0.24113922893104198,
        min_iou=0.10300687285223367,
        mean_soft_iou=0.23380033808755352,
        frames_tested=16,
        worst_frame=1001,
        worst_edge_only=False,
        note='mean IoU 0.241 below 0.95',
    ),
    Element(
        element_id='TVC_SHOTS_sh0230_BG01_v003__matteL110__G',
        shot='TVC_SHOTS_sh0230_BG01_v003_roto_v02',
        matte='TVC_SHOTS_sh0230_BG01_v003_matte_L110_v02',
        channel='G',
        labels=('L110/green',),
        uuids=('105efbbe-6506-4461-8eeb-18a3b48b306e',),
        tier='excluded',
        mean_iou=0.06370841336524777,
        min_iou=0.018301057547040242,
        mean_soft_iou=0.15009928196571512,
        frames_tested=5,
        worst_frame=1021,
        worst_edge_only=False,
        note='delivered matte was rendered from a different save than the archived project (hair animates ~20 frames past the last key); also 87% single-frame hair strokes',
    ),
    Element(
        element_id='TVC_SHOTS_sh0230_BG01_v003__matteL110__B',
        shot='TVC_SHOTS_sh0230_BG01_v003_roto_v02',
        matte='TVC_SHOTS_sh0230_BG01_v003_matte_L110_v02',
        channel='B',
        labels=('L110/blue',),
        uuids=('606c55b8-81f8-4d46-a89f-dcdce430fc32',),
        tier='excluded',
        mean_iou=0.06039130762715432,
        min_iou=0.020271526873721406,
        mean_soft_iou=0.14845403311531852,
        frames_tested=5,
        worst_frame=1021,
        worst_edge_only=False,
        note='delivered matte was rendered from a different save than the archived project (hair animates ~20 frames past the last key); also 87% single-frame hair strokes',
    ),
    Element(
        element_id='TVC_SHOTS_sh0230_BG01_v003__matteL110__R',
        shot='TVC_SHOTS_sh0230_BG01_v003_roto_v02',
        matte='TVC_SHOTS_sh0230_BG01_v003_matte_L110_v02',
        channel='R',
        labels=('L110/red',),
        uuids=('6d124469-8cb1-4938-85f3-d8d765303820',),
        tier='excluded',
        mean_iou=0.056934485591002316,
        min_iou=0.015159660251585851,
        mean_soft_iou=0.14516016598191553,
        frames_tested=5,
        worst_frame=1031,
        worst_edge_only=False,
        note='delivered matte was rendered from a different save than the archived project (hair animates ~20 frames past the last key); also 87% single-frame hair strokes',
    ),
)

TARGETS: tuple[Element, ...] = tuple(e for e in ELEMENTS if e.is_target)


def by_id(element_id: str) -> Element:
    for e in ELEMENTS:
        if e.element_id == element_id:
            return e
    raise KeyError(f'no element {element_id!r}; have {[e.element_id for e in ELEMENTS]}')
